### PR TITLE
Implemented createNewWindow option

### PR DESCRIPTION
**Pull request by imcovangent**
A new option was added for url type app launcher to open the URL in a new browser window.

### CODE REVIEW

**Comment by imcovangent** [comment]
@trungleduc Can you have a look at this draft PR and let me know if you agree on the implementation. Then I will finish it up accordingly.

**Comment by trungleduc** [comment]
Thanks for opening the PR, it looks neat to me 🚀

**Comment by imcovangent** [comment]
I've updated the README and usage documentation. This PR is ready for review (and hopefully for completion as well). :)

**Comment by trungleduc** [comment]
Thanks!

**Comment by imcovangent** [comment]
You're welcome, looking forward to the next release! :)

**Comment by trungleduc** [comment]
0.1.7 is out

**Pull request merged**
